version: '3.8'

services:
  backend:
    build: 
      context: ./TaskPlatform
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TaskPlatformDbContext=Host=postgres;Database=task_platform_db;Username=postgres;Password=1111
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./TaskPlatformFront
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4300:80"
    depends_on:
      - backend

  migrations:
    build:
      context: ./TaskPlatform
      dockerfile: Dockerfile.migrations
    container_name: migrations
    environment:
      - ConnectionStrings__TaskPlatformDbContext=Host=postgres;Database=task_platform_db;Username=postgres;Password=1111
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: task_platform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
